name: CI

on:
  push:
    branches: [main]


jobs:
  build:
    # The type of runner that the job will run on
    name: Upload to S3 and Initializing Code Deploy
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout Repository
      uses: actions/checkout@v2

    # Ref: https://github.com/marketplace/actions/packer-github-actions
    - name: setup node 
      uses: actions/setup-node@v2
      with: 
          node-version: '12.x'
           
    - name: install dependencies
      run:  npm install
    - name: check test cases
      run:  npm test
      